# Headless Service
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-hl
spec:
  ClusterIP: None
  ports:
    - protocol: TCP
      port: 2367
      targetPort: 2367
  selector:
    name: rabbitmq
    project: roboshop
    tier: db
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
    - protocol: TCP
      port: 2367
      targetPort: 2367
  selector:
    name: rabbitmq
    project: roboshop
    tier: db
---
apiVersion: v1
kind: StatefulSet
metadata:
  name: rabbitmq
  labels:
    name: rabbitmq
    project: roboshop
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rabbitmq
      project: roboshop
      tier: db
  template:
    metadata:
      name: rabbitmq
      labels:
        name: rabbitmq
        project: roboshoop
        tier: db
    spec:
      containers:
        - name: rabbitmq
          image: srikanthsuthari/rabbitmq:v2
          