# Headless Service
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-hl
  namespace: roboshop
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      port: 2367
      targetPort: 2367
  selector:
    component: rabbitmq
    project: roboshop
    tier: db
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  ports:
    - protocol: TCP
      port: 2367
      targetPort: 2367
  selector:
    component: rabbitmq
    project: roboshop
    tier: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  serviceName: rabbitmq-hl
  replicas: 1
  selector:
    matchLabels:
      component: rabbitmq
      project: roboshop
      tier: db
  template:
    metadata:
      name: rabbitmq
      labels:
        component: rabbitmq
        project: roboshop
        tier: db
    spec:
      containers:
        - name: rabbitmq
          image: srikanthsuthari/rabbitmq:v2
          volumeMounts:
            - name: rabbitmq
              mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: roboshop-ebs
        resources:
          requests:
            storage: 1Gi