apiVersion: v1
kind: Service
metadata:
  name: mongodb-hl
  namespace: roboshop
spec:
  clusterIP: None
  selector:
    component: mongodb
    project: roboshop
    tier: db
  ports:
  - protocol: TCP
    port: 27017     #Service Port
    targetPort: 27017     #Container Port
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    component: mongodb
    project: roboshop
    tier: db
  ports:
  - protocol: TCP
    port: 27017     #Service Port
    targetPort: 27017     #Container Port
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
spec:
  serviceName: mongodb-hl     # this should be head less service name
  replicas: 2       # by default is 1
  selector:
    matchLabels:
      component: mongodb
      project: roboshop
      tier: db
  template:
    metadata:
      name: mongodb
      labels:
        component: mongodb
        project: roboshop
        tier: db
    spec:
      containers:
        - name: mongodb
          image: srikanthsuthari/mongodb:v2
          volumeMounts:
            - name: mongodb
              mountPath: /data/db
    # This is PVC
  volumeClaimTemplates:
    - metadata:
        name: mongodb
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "roboshop-ebs"
        resources:
          requests:
            storage: 1Gi

