# HeadLess Service
apiVersion: v1
kind: Service
metadata:
  name: mysql-hl
  namespace: roboshop
spec:
  selector:
    project: roboshoop
    component: mysql
    tier: db
  clusterIP: None
  ports:
    - protocol: TCP
      port: 3306    # Service Port
      targetPort: 3306      # Container Port
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
    project: roboshoop
    component: mysql
    tier: db
  ports:
    - protocol: TCP
      port: 3306    # Service port
      targetPort:  3306   # Container port
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: roboshop
spec:
  serviceName: mysql-hl   # This should be the headless service
  replicas: 1
  selector:
    matchLabels:
      project: roboshoop
      component: mysql
      tier: db
  template:
    metadata:
      name: mysql
      labels:
        project: roboshoop
        component: mysql
        tier: db
    spec:
      containers:
        - name: mysql
          image: srikanthsuthari/mysql:v2
          volumeMounts:
            - name: mysql
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: roboshop-ebs
        resources:
          requests:
            storage: 1Gi