apiVersion: v1
kind: Service
metadata:
  name: redis-hl
  namespace: roboshop
spec:
  clusterIP: None
  selector:
    component: redis
    project: roboshop
    tier: db
  ports:
    - protocol: TCP
      port: 6379    # Service Port
      targetPort: 6379  # Container Port
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
spec:
  selector:
    component: redis
    project: roboshop
    tier: db
  ports:
    - protocol: TCP
      port: 6379    # Service Port
      targetPort: 6379  # container Port
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: roboshop
spec:
  serviceName: redis-hl     # name of the headless service
  replicas: 2
  selector:
    matchLabels:
      component: redis
      project: roboshop
      tier: db
  template:
    metadata:
      name: redis
      labels:
        component: redis
        project: roboshop
        tier: db
    spec:
      containers:
        - name: redis
          image: srikanthsuthari/redis:v1
          volumeMounts:
            - name: redis
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: roboshop
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: roboshop-ebs
        resources:
          requests:
            storage: 1Gi